language: java
jdk:
- openjdk10
scala:
- 2.10.4
before_install:
  - cd ../
  - git clone https://github.com/SciSpark/SciSpark
  - cd SciSpark/
  - sbt 1.0 assembly
  - mvn install:install-file -Dfile=target/scala-2.11/SciSpark.jar -DgroupId=org.dia -DartifactId=scispark -Dversion=1 -Dpackaging=jar
  - cd Weather-Integrator/