language: java
jdk:
- openjdk10

matrix:
  include:
  - scala: 2.10.6
    env: SPARK_VERSION=1.6.0 SCALA_VERSION=2.10.6
  - scala: 2.10.6
    env: SPARK_VERSION=2.0.0 SCALA_VERSION=2.10.6
  - scala: 2.11.2
    env: SPARK_VERSION=2.0.0 SCALA_VERSION=2.11.2

before_install:
  - cd ../
  - git clone https://github.com/SciSpark/SciSpark
  - cd SciSpark/
  - sbt clean assembly
  - mvn install:install-file -Dfile=target/scala-2.11/SciSpark.jar -DgroupId=org.dia -DartifactId=scispark -Dversion=1 -Dpackaging=jar
  - cd Weather-Integrator/