language: java
jdk:
- openjdk10
scala:
- 2.11.0
before_install:
  - git clone https://github.com/SciSpark/SciSpark
  - cd SciSpark/
  - assembly
  - mvn install:install-file -Dfile=target/scala-2.11/SciSpark.jar -DgroupId=org.dia -DartifactId=scispark -Dversion=1 -Dpackaging=jar